# Generated by Django 4.2 on 2023-09-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('TNK', 'Танки'), ('HIL', 'Хилы'), ('DD', 'ДД'), ('MCH', 'Торговцы'), ('GMA', 'Гилдмастеры'), ('QMA', 'Квестгиверы'), ('BLM', 'Кузнецы'), ('TAN', 'Кожевники'), ('PMK', 'Зельевары'), ('SMA', 'Мастера заклинаний')], max_length=20),
        ),
    ]
